import type { Metadata } from "next";
import "./globals.css";
import { outfit, questrial } from "./fonts";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Hivency – Creative Digital Agency WordPress Theme",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${questrial.variable} ${outfit.variable}`}>
      <body className={questrial.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
