import type { Metadata } from "next";
import "./globals.css";
import { outfit, questrial, icomoon } from "./fonts";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Hivency – Creative Digital Agency WordPress Theme",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${questrial.variable} ${outfit.variable} ${icomoon.variable}`}
    >
      <body className={`${questrial.className} h-[1300px] text-black-100`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
